spring:
  application:
    name: ares-search
  profiles:
    active: "@active.spring.profile@"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    open-in-view: false
GROOVY_TURN_OFF_JAVA_WARNINGS: true
